steps:
  # Install dependencies
  - name: 'gcr.io/$PROJECT_ID/angular'
    args: [ 'npm', 'install' ]

  # Run integration tests
  - name: 'gcr.io/$PROJECT_ID/angular'
    args: [ 'npm', 'run', 'test' ]

  # Run end-to-end tests
  - name: 'gcr.io/$PROJECT_ID/angular'
    args: [ 'npm', 'run', 'e2e' ]

  # Build the application
  - name: 'gcr.io/$PROJECT_ID/angular'
    args: [ 'npm', 'run', 'build' ]

  # Deploy to firebase
  # https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/firebase
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: [ 'deploy', '--only', 'hosting' ]
